### ISSUE TITLE
DatabaseDocumentToRecord converts empty arrays into strings

### ISSUE THREAD

**Issue by le-on** [homalg-project/ArangoDBInterface#2]
If a database document has an attribute whose value is an empty array, for example `{ a : [ ] }`, then DatabaseDocumentToRecord returns this as `rec(a := "[ ]")`.
On the other hand, if the document is of the form `{ a : { b : [ ] } }`, then DatabaseDocumentToRecord returns `rec(a := rec(b := [ ]))` as expected.

**Comment by mohamed-barakat** [comment]
Fixed. You can pull.
